### PR TITLE
Feature/eslint support

### LINKED ISSUE #2: Replace jshint by eslint
Following our discussion in #1

### PR DESCRIPTION
**Pull request by mrister**
Adds support for eslint and removes jshint
Adjusts code to be lint free
Adjusts makefile to use eslint
Closes #2 

Note some projects will need tuning of eslint config files (.eslintrc and .eslintignore)

Note that eslint installed globally does not work with plugins installed locally (node_modules of project) so makefile installs all globally (like it does mocha and istanbul).
https://github.com/eslint/eslint/issues/1238

### CODE REVIEW

**Comment by PuKoren** [comment]
LGTM, having modules installed globally makes sense

**Comment by jkernech** [comment]
LGTM

**Comment by mrister** [comment]
@PuKoren @jkernech  Updated the branch with master so need LGTMs again :-)

**Comment by ykhatal** [comment]
LGTM

**Pull request merged**
